- name: delete route
  openshift_v1_route:
    name: '{{ sync_server_route_name }}'
    namespace: '{{ namespace }}'
    state: absent

- name: delete services
  k8s_v1_service:
    name: '{{ item }}'
    namespace: '{{ namespace }}'
    state: absent
  with_items:
  - fh-sync-server
  - mongodb
  - redis

- name: delete deployments
  k8s_apps_v1beta1_deployment:
    name: '{{ item }}'
    namespace: '{{ namespace }}'
    state: absent
  with_items:
  - fh-sync-server
  - mongodb
  - redis

- name: delete secrets
  k8s_v1_secret:
    name: '{{ item }}'
    namespace: '{{ namespace }}'
    state: absent
  with_items:
  - fh-sync-server
  - mongodb

- name: delete persistent volume claims
  k8s_v1_persistent_volume_claim:
    name: '{{ item }}'
    namespace: '{{ namespace }}'
    state: absent
  with_items:
  - mongodb
